version: "3.3"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "<path to presist to local machine>/mongodb-data:/data/db"
    restart: "always"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "<path to presist to local machine>/opensearch-data:/usr/share/opensearch/data"
    restart: "always"

  graylog:
    hostname: "server"
    image: "graylog/graylog:5.0"
    depends_on:
      - opensearch
      - mongodb
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      # You MUST set a secret to secure/pepper the stored user passwords here. Use at least 64 characters.
      # Generate one by using for example: pwgen -N 1 -s 96
      # ATTENTION: This value must be the same on all Graylog nodes in the cluster.
      # Changing this value after installation will render all user sessions and encrypted values in the database invalid. (e.g. encrypted access tokens)
      GRAYLOG_PASSWORD_SECRET: "somnq1PC6OLkYE94wC0R9YUMMYW1zYTFjghwkvaMyLWE5xB33DCtdLslukpcpZ7yMzwrFkBDqkihLdZf0BKLSvZwcK8MgobP"
      
      # You MUST specify a hash password for the root user (which you only need to initially set up the
      # system and in case you lose connectivity to your authentication backend)
      # This password cannot be changed using the API or via the web interface. If you need to change it,
      # modify it in this file.
      # Create one by using for example: echo -n yourpassword | shasum -a 256
      # and put the resulting hash value into the following line
      # CHANGE THIS!
      GRAYLOG_ROOT_PASSWORD_SHA2: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
      GRAYLOG_ROOT_USERNAME: "admin"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    # - "5044:5044/tcp"   # Beats
    # - "5140:5140/udp"   # Syslog
    # - "5140:5140/tcp"   # Syslog
    # - "5555:5555/tcp"   # RAW TCP
    # - "5555:5555/udp"   # RAW TCP
    - "1514:1514/tcp"   # Systemlog tcp
    - "1514:1514/udp"   # Systemlog upd
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    # - "13301:13301/tcp" # Forwarder data
    # - "13302:13302/tcp" # Forwarder config
    volumes:
      - "<path to presist to local machine>/greylog-data:/usr/share/graylog/data/data"
      - "<path to presist to local machine>/greylog-journal:/usr/share/graylog/data/journal"
    restart: "always"
